name: Feature request
description: Propose an enhancement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Suggested behavior/API/CLI changes.
    validations:
      required: true
